### ISSUE TITLE
Issue with observation normalization when len(observation_spec) > 1

### ISSUE THREAD

**Issue by ChengshuLi** [tensorflow/agents#10]
Hi,

I am trying to train ppo with observation spec that has len > 1. 

E.g. my gym environment looks something like this:
```
self.observation_space = gym.spaces.Dict({
    'observation': gym.spaces.Box(low=0.0, high=1.0,
                                  shape=(128, 128, 4),
                                  dtype=np.float32),
    'state': gym.spaces.Box(low=-np.inf, high=np.inf, shape=(self.sensor_dim,), dtype=np.float32)
})
```

And the corresponding tf env looks something like this:
```
observation_spec = collections.OrderedDict([
    ('observation', tensor_spec.BoundedTensorSpec(shape=(128, 128, 4),
                                                  dtype=tf.float32,
                                                  minimum=0.0,
                                                  maximum=1.0)),
    ('state', tensor_spec.BoundedTensorSpec(shape=(19),
                                            dtype=tf.float32,
                                            minimum=-np.inf,
                                            maximum=np.inf))
    ])
```
I modified the `tf_agents/networks/actor_distribution_network.py` and `tf_agents/networks/value_network.py` to accept multiple inputs and concatenate the results (drew inspiration from `preprocessing_layers` and `preprocessing_combiner` of `tf_agents/networks/encoding_network.py`).

If I set `normalize_observations=False` for my `ppo_agent.PPOAgent`, the training (`tf_agents/agents/ppo/examples/train_eval.py`) works fine.

However, when I set `normalize_observations=True`, which is the default choice, the training breaks. The problem occurs in `tf_agents/utils/tensor_normalizer.py`. I modified the `_update_ops` function to update each component of the observation separately. 

Then I got a new error (you can see below for the error log). The gist is basically when calling `initialize()` for  `eval_py_policy = py_tf_policy.PyTFPolicy(tf_agent.policy())`, it complains some of the variables are `DictWrapper` of `tf.Variable` instead of `tf.Variable`. For example, the following is a variable of the tf policy:
DictWrapper({'state': <tf.Variable 'normalize_observations/normalize_observations/var_sum_1:0' shape=(19,) dtype=float32>, 'observation': <tf.Variable 'normalize_observations/normalize_observations/var_sum:0' shape=(128, 128, 4) dtype=float32>}).

I would really appreciate if anyone could give me some suggestions on how to resolve this. Thanks a ton!

Error log:
```
Traceback (most recent call last):
  File "train_eval_p2p_nav_ppo.py", line 413, in <module>
    tf.app.run()
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train_eval_p2p_nav_ppo.py", line 408, in main
    use_rnns=FLAGS.use_rnns)
  File "train_eval_p2p_nav_ppo.py", line 341, in train_eval
    callback=eval_metrics_callback,
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/metrics/metric_utils.py", line 94, in compute_summaries
    results = compute(metrics, environment, policy, num_episodes)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/metrics/metric_utils.py", line 55, in compute
    policy_state = policy.get_initial_state(environment.batch_size)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/policies/py_policy.py", line 104, in get_initial_state
    return self._get_initial_state(batch_size)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/policies/py_tf_policy.py", line 157, in _get_initial_state
    self.initialize(batch_size)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/policies/py_tf_policy.py", line 104, in initialize
    self.session.run(tf.initializers.variables(self._tf_policy.variables()))
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 2834, in variables_initializer
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 2834, in <listcomp>
    return control_flow_ops.group(*[v.initializer for v in var_list], name=name)
AttributeError: '_DictWrapper' object has no attribute 'initializer'
```

**Comment by ChengshuLi** [comment]
I tentatively solved this issue by changing
https://github.com/tensorflow/agents/blob/beedf60a6fb9cc0f6efdc4d6d74e72613c83236f/tf_agents/policies/py_tf_policy.py#L104-L105
to
```
self.session.run(
    tf.initializers.variables(tf.contrib.framework.nest.flatten(self._tf_policy.variables())))
```
Do you think this is the right approach? Not sure if this will break other things. 

Thanks!

**Comment by sguada** [comment]
This seems a reasonable fix, feel free to create a PR to fix it.

Thanks,

**Comment by oars** [comment]
Normalization should handle the nested inputs now, and the fix you suggested got integrated. Thanks for reporting the issue!
