### ISSUE TITLE
error when running 6_reinforce_tutorial.ipynb

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#100]
hello team 

I'm running colab example n. 6 but I get this error while collecting data

Traceback (most recent call last):
  File "C:\Users\shock\Desktop\workspace\test_colab\test_reinforce.py", line 121, in <module>
    collect_episode(train_env, collect_policy, num_episodes=1)
  File "C:\Users\shock\Desktop\workspace\test_colab\test_reinforce.py", line 66, in collect_episode
    replay_buffer.add_batch(traj)
  File "C:\Users\shock\Anaconda3\envs\agents\lib\site-packages\tf_agents\replay_buffers\replay_buffer.py", line 65, in add_batch
    return self._add_batch(items)
  File "C:\Users\shock\Anaconda3\envs\agents\lib\site-packages\tf_agents\replay_buffers\tf_uniform_replay_buffer.py", line 131, in _add_batch
    write_rows = self._get_rows_for_id(id_)
  File "C:\Users\shock\Anaconda3\envs\agents\lib\site-packages\tf_agents\replay_buffers\tf_uniform_replay_buffer.py", line 364, in _get_rows_for_id
    id_mod = tf.math.mod(id_, self._max_length)
AttributeError: module 'tensorflow._api.v2.math' has no attribute 'mod'

**Comment by kuanghuei** [comment]
I re-run it on Google Colab (you can find the link to it on top of the colab) with:
`tf-nightly-1.14.1.dev20190508`
`tf-agents-nightly-0.2.0.dev20190430`
`tfp-nightly-0.7.0.dev20190508`

Seems okay. Can you cross-check your environment with the colab?
