### ISSUE TITLE
'AtariPreprocessing' object has no attribute 'spec'`

### ISSUE THREAD

**Issue by ageron** [tensorflow/agents#123]
I'm getting an error `AttributeError: 'AtariPreprocessing' object has no attribute 'spec'` when trying to create a Breakout game wrapped with both `AtariPreprocessing` and `FrameStack4`.

I pushed PR #118 which would solve this issue. :)

```python
>>> from tf_agents.environments import suite_atari
>>> from tf_agents.environments.atari_preprocessing import AtariPreprocessing
>>> from tf_agents.environments.atari_wrappers import FrameStack4
>>>
>>> env = suite_atari.load(
...     "BreakoutNoFrameskip-v4",
...     max_episode_steps=27000,
...     gym_env_wrappers=[AtariPreprocessing, FrameStack4])
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/tf_agents/environments/suite_atari.py", line 87, in load
    auto_reset=False)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/tf_agents/environments/suite_gym.py", line 118, in wrap_env
    gym_env = wrapper(gym_env)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/tf_agents/environments/atari_wrappers.py", line 35, in __init__
    super(FrameStack4, self).__init__(env)
  File "/Users/ageron/miniconda3/envs/testagents/lib/python3.6/site-packages/gym/core.py", line 217, in __init__
    self.spec = self.env.spec
AttributeError: 'AtariPreprocessing' object has no attribute 'spec'
  In call to configurable 'wrap_env' (<function wrap_env at 0x144fbb488>)
  In call to configurable 'load' (<function load at 0x144fbbbf8>)
```

**Comment by emailweixu** [comment]
I also encountered this problem. Is there any plan to solve this issue (perhaps by merging PR #118)?

**Comment by tfboyd** [comment]
I wish I could be sure the issue was fixed. But this is over a year old and the PR was merged.  If you (anyone reading this) have a similar issue please open a new issue.

**Comment by ageron** [comment]
I just tested the code example above, and it works fine now. Thanks.
