### ISSUE TITLE
Sample action outside the valid range

### ISSUE THREAD

**Issue by ChengshuLi** [tensorflow/agents#13]
Hi,

NormalProjectionNetwork only normalize the mean of the tfp.distributions.Normal to be within [action_spec.min, action_spec.max]. 
https://github.com/tensorflow/agents/blob/efc2e3d86b8273283a68b783d39094d695f55d49/tf_agents/networks/normal_projection_network.py#L132

However, since the standard deviation is non-zero, it's possible for the actor to sample an action that is outside the valid range. For example, say my action spec is 
```
BoundedTensorSpec(shape=(2,), dtype=tf.float32, name=None, minimum=array([-0.02, -0.02], dtype=float32), maximum=array([0.02, 0.02], dtype=float32))
```
When I trained PPO, it used the default `init_action_stddev=0.35` 
https://github.com/tensorflow/agents/blob/efc2e3d86b8273283a68b783d39094d695f55d49/tf_agents/networks/actor_distribution_network.py#L40-L48
Therefore, most of the sampled actions are outside the valid [-0.02, 0.02] range. 

Here are a few solutions that I could think of
1) change from tfp.distributions.Normal to tfp.distributions.TrunNormal 
Change
https://github.com/tensorflow/agents/blob/efc2e3d86b8273283a68b783d39094d695f55d49/tf_agents/networks/normal_projection_network.py#L148
to
```
    return self.output_spec.build_distribution(loc=means,
                                               scale=stds,
                                               low=tf.constant(self._sample_spec.minimum),
                                               high=tf.constant(self._sample_spec.maximum))
```
However, I got the following error. I spent some time debugging but no luck so far.
```
Traceback (most recent call last):
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1819, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 1 and 2 for 'tf_uniform_replay_buffer/TFUniformReplayBuffer_1/ResourceScatterUpdate_6' (op: 'ResourceScatterUpdate') with input shapes: [], [1], [3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_eval_p2p_nav_ppo.py", line 397, in <module>
    tf.app.run()
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train_eval_p2p_nav_ppo.py", line 392, in main
    use_rnns=FLAGS.use_rnns)
  File "train_eval_p2p_nav_ppo.py", line 258, in train_eval
    num_episodes=collect_episodes_per_iteration).run()
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 159, in run
    name='driver_loop'
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3477, in while_loop
    return_same_structure)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2998, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2923, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 98, in loop_body
    observer_ops = [observer(traj) for observer in self._observers]
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 98, in <listcomp>
    observer_ops = [observer(traj) for observer in self._observers]
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/module/module.py", line 120, in enter_name_scope
    return unbound_method(self, *args, **kwargs)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/replay_buffers/replay_buffer.py", line 65, in add_batch
    return self._add_batch(items)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/module/module.py", line 120, in enter_name_scope
    return unbound_method(self, *args, **kwargs)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/replay_buffers/tf_uniform_replay_buffer.py", line 136, in _add_batch
    write_data_op = self._data_table.write(write_rows, items)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/replay_buffers/table.py", line 132, in write
    for (slot, value) in zip(flattened_slots, flattened_values)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tf_agents/replay_buffers/table.py", line 132, in <listcomp>
    for (slot, value) in zip(flattened_slots, flattened_values)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 302, in scatter_update
    name=name))
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 1271, in resource_scatter_update
    updates=updates, name=name)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 800, in _apply_op_helper
    op_def=op_def)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3473, in create_op
    op_def=op_def)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1983, in __init__
    control_input_ops)
  File "/cvgl2/u/chengshu/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1822, in _create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 1 and 2 for 'tf_uniform_replay_buffer/TFUniformReplayBuffer_1/ResourceScatterUpdate_6' (op: 'ResourceScatterUpdate') with input shapes: [], [1], [3].
```

2) change `init_action_stddev` to a smaller number, e.g. 0.001
3) clip the action within the `step` function of my environment. 

Which solution do you think is the best to solve this issue? 

Thanks a ton. Any help will be greatly appreciated.

**Comment by samfishman** [comment]
Hi Chengshu,

You're correct that it's possible for the NormalProjectionNetwork to generate actions that are outside of the spec. Squashing the mean to be within spec is an approximation meant to keep the actions mostly within spec but it fails when the bounds are too small.

The bug you're seeing with your first possible solution is that the `low` and `high` parameters don't have the same shape as `loc` and `scale`. You can correct that by using `low=tf.broadcast_to(self._sample_spec.minimum, tf.compat.v2.shape(means))` and `high=tf.broadcast_to(self._sample_spec.maximum, tf.compat.v2.shape(means))`. However, this solution actually won't work still because the TruncatedNormal distribution doesn't have a closed-form KL divergence, which PPO relies on.

Instead, I suggest you use a combination of (2) and (3). Select an `init_action_stddev` to a value such that most samples will be within bounds - e.g. you could set it to `(maximum - minimum) / 6` so that there are 3 standard deviations of wiggle room on either side of the center before you go out of bounds.

Then, you can use the [`ActionClipWrapper`](https://github.com/tensorflow/agents/blob/master/tf_agents/environments/wrappers.py#L298-L320) to ensure that even when samples are out of bounds, they get clipped. To use this wrapper, pass your existing environment to it: `env = ActionClipWrapper(env)`.

I am closing this issue, but feel free to reopen if this does not fix your problem.

**Comment by ChengshuLi** [comment]
Thank you very much for your detailed explanation. Yes this fixed my problem. Thanks again.
