### ISSUE TITLE
tf_agent.policy.action(time_step) under TF2 throws exception

### ISSUE THREAD

**Issue by ideenfix** [tensorflow/agents#141]
After training the Q-network e.g. for "Pong" from Atari I want to play some epochs based on the trained weights.

While execution of tf_agent.policy.action(time_step) the following exception was thrown

> Traceback (most recent call last):
  File "D:/git/Deep-Reinforcement-Learning-Hands-On/Chapter07/dqn_basic_play_tf_standalone.py", line 415, in <module>
    action_step, state, info = tf_agent.policy.action(time_step)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\policies\tf_policy.py", line 243, in action
    step = action_fn(time_step=time_step, policy_state=policy_state, seed=seed)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\policies\tf_policy.py", line 426, in _action
    distribution_step = self._distribution(time_step, policy_state)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\policies\greedy_policy.py", line 72, in _distribution
    time_step, policy_state)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\policies\tf_policy.py", line 293, in distribution
    step = self._distribution(time_step=time_step, policy_state=policy_state)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\policies\q_policy.py", line 79, in _distribution
    time_step.observation, time_step.step_type, policy_state)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\networks\network.py", line 151, in __call__
    return super(Network, self).__call__(inputs, *args, **kwargs)
  File "D:\pyenv\py36tf2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "D:\pyenv\py36tf2\lib\site-packages\tf_agents\networks\q_network.py", line 135, in call
    return self._q_value_layer(state), network_state
  File "D:\pyenv\py36tf2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 712, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "D:\pyenv\py36tf2\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1048, in call
    outputs = gen_math_ops.mat_mul(inputs, self.kernel)
  File "D:\pyenv\py36tf2\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6285, in mat_mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix. Instead it has shape [512] [Op:MatMul]

Some information to my environment:
OS: nt Windows 10

Python:3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
Tensorflow: 2.0.0-beta1
TF-Agent:0.2.0

Attached my python environment based on pip list
[py36tf2.txt](https://github.com/tensorflow/agents/files/3295278/py36tf2.txt)

Attached my Nvidia configuration
[nvidia.txt](https://github.com/tensorflow/agents/files/3295295/nvidia.txt)

Attached my selfrunning (hopyfully) python script:
[dqn_basic_play_tf_standalone.py.txt](https://github.com/tensorflow/agents/files/3295282/dqn_basic_play_tf_standalone.py.txt)

Attached the trained weights:
[20190613-160156.data-00000-of-00002.txt](https://github.com/tensorflow/agents/files/3295288/20190613-160156.data-00000-of-00002.txt)
[20190613-160156.data-00001-of-00002.txt](https://github.com/tensorflow/agents/files/3295289/20190613-160156.data-00001-of-00002.txt)
[20190613-160156.index.txt](https://github.com/tensorflow/agents/files/3295290/20190613-160156.index.txt)

**Comment by ideenfix** [comment]
I've checked this example also with tf-nightly-gpu and got the same exception.

I guess the problem is that the output of the convnet (encoder) has shape [512] and not [1,512]. Contemporarily I run the colab cartpole example. As this example is without convnet it's running as the time_step.observation has shape [1, 4].

Hope that this remark helps

**Comment by sguada** [comment]
It seems that the environment is missing the batching dimension.

```
env = suite_gym.load(
        params['env_name'],
        gym_env_wrappers=wrap_dqn()
    )
env = batched_py_environment.BatchedPyEnvironment([env])
```

**Comment by ideenfix** [comment]
Now it's running. Thx alot. 

But leads to the next problem as BatchPyEnvironment doesn't forward env.render(). However, this is not a problem to solve it.

**Comment by kbanoop** [comment]
Closing this.

We are tracking the issue with BatchPyEnvironment.render internally, but please feel free to create an external one as well.
