### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'preprocessing_layers'

### ISSUE THREAD

**Issue by marcelyz** [tensorflow/agents#150]
log:

python tf_agents/agents/dqn/examples/v1/train_eval_gym.py \
  --root_dir=$HOME/tmp/dqn_v1/gym/CartPole-v0/ \
  --alsologtostderr
WARNING: Logging before flag parsing goes to stderr.
W0628 17:39:22.941468 4649018816 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0628 17:39:23.080335 4649018816 deprecation_wrapper.py:119] From /Users/apple/.conda/envs/agents/lib/python3.7/site-packages/tf_agents/utils/eager_utils.py:221: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0628 17:39:23.144483 4649018816 deprecation_wrapper.py:119] From tf_agents/agents/dqn/examples/v1/train_eval_gym.py:295: The name tf.enable_resource_variables is deprecated. Please use tf.compat.v1.enable_resource_variables instead.

Traceback (most recent call last):
  File "tf_agents/agents/dqn/examples/v1/train_eval_gym.py", line 305, in <module>
    app.run(main)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_agents/agents/dqn/examples/v1/train_eval_gym.py", line 300, in main
    num_iterations=FLAGS.num_iterations)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "tf_agents/agents/dqn/examples/v1/train_eval_gym.py", line 125, in train_eval
    fc_layer_params=fc_layer_params)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/tf_agents/networks/network.py", line 80, in capture_init
    init(self, **kwargs)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/tf_agents/networks/q_network.py", line 114, in __init__
    dtype=dtype)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/Users/apple/.conda/envs/agents/lib/python3.7/site-packages/tf_agents/networks/network.py", line 80, in capture_init
    init(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'preprocessing_layers'
  In call to configurable 'EncodingNetwork' (<function _NetworkMeta.__new__.<locals>.capture_init at 0xb34f6dc80>)
  In call to configurable 'QNetwork' (<function _NetworkMeta.__new__.<locals>.capture_init at 0xb34f6dea0>)
  In call to configurable 'train_eval' (<function train_eval at 0x10e56b840>)

![屏幕快照 2019-06-28 下午5 40 24 (2)](https://user-images.githubusercontent.com/22769274/60333530-e1f74400-99cb-11e9-8ea3-7f089105fef6.png)

**Comment by Addyvan** [comment]
I am having the same issue.

**Comment by tfboyd** [comment]
Closing as stale.
