### ISSUE TITLE
How to see model topology / log graph in TensorBoard

### ISSUE THREAD

**Issue by andreas-repp** [tensorflow/agents#162]
When I run the [PPO v2 example](https://github.com/tensorflow/agents/blob/master/tf_agents/agents/ppo/examples/v2/train_eval.py), I get a lot of metrics in tensorboard. However, I cannot see a graph. 

What do I have to do to see the graph in Tensorboard? Or which other way can I use to debug my model topology?

**Comment by kuanghuei** [comment]
It is a tf2 eager mode example. You won't see a graph for the dynamic part. Even for the part that is wrapped with tf.function decorator, I don't think it is not trivial for tensorflow to visualize the graph at this point.

**Comment by samfishman** [comment]
Actually, you can enable graph export in v2. You'll need to call tf.summary.trace_on() before the code you want to trace the graph for (e.g. L224 if you just want the train step), and then call tf.summary.trace_off() after the code completes. Since you only need one trace of the graph, I would recommend wrapping these calls with `if global_step_val == 0:` so that you don't produce traces every step.

More documentation can be found [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/summary/trace_on). Feel free to reopen this issue if you have any trouble getting the trace to work.

**Comment by andreas-repp** [comment]
@samfishman: Thanks for the hint. Unfortunatly, the graph is split up into single operation blocks in TensorBoard and therefore not helpfull. Just as a note: It's not ` tf.summary.trace_off()` that needs to be called but ` tf.summary.trace_export()` to actually save the trace.

To get a better idea of the network, I now tried to use the keras model summary function on the actor_net after it's first usage. Unfortunatly, I get only a part of the result and and an exception:

``` 
Model: "ActorDistributionRnnNetwork"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_mlp/conv2d (Conv2D)    multiple                  160       
_________________________________________________________________
input_mlp/conv2d (Conv2D)    multiple                  3480      
_________________________________________________________________
input_mlp/conv2d (Conv2D)    multiple                  5208      
_________________________________________________________________
input_mlp/conv2d (Conv2D)    multiple                  6944      
_________________________________________________________________
flatten (Flatten)            multiple                  0         
_________________________________________________________________
input_mlp/dense (Dense)      multiple                  131328    
_________________________________________________________________
dynamic_unroll (DynamicUnrol multiple                  525312    
_________________________________________________________________
flatten_1 (Flatten)          multiple                  0         
_________________________________________________________________
CategoricalProjectionNetwork multiple                  771       
=================================================================
Traceback (most recent call last):
  File "/home/predator2080/.pycharm_helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/predator2080/.pycharm_helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/predator2080/.pycharm_helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/predator2080/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/tmp/pycharm_project_372/ppo_train_eval.py", line 280, in <module>
    app.run(main)
  File "/home/predator2080/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/predator2080/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/pycharm_project_372/ppo_train_eval.py", line 275, in main
    use_rnns=FLAGS.use_rnns)
  File "/home/predator2080/.local/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/predator2080/.local/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/predator2080/.local/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/tmp/pycharm_project_372/ppo_train_eval.py", line 166, in train_eval
    actor_net.summary()
  File "/home/predator2080/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1490, in summary
    print_fn=print_fn)
  File "/home/predator2080/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/layer_utils.py", line 230, in print_summary
    model._check_trainable_weights_consistency()
AttributeError: 'ActorDistributionRnnNetwork' object has no attribute '_check_trainable_weights_consistency'
```

1. Do you have an idea what needs to be changed to fix this error?
2. Do you know how why the output shape is stated as "multiple"? Is there a way to fix this to get more insight?
