### ISSUE TITLE
ActorDistributionNetwork crashes when action_spec is not a tensor_spec

### ISSUE THREAD

**Issue by j0rd1smit** [tensorflow/agents#197]
`ActorDistributionNetwork`  does not work with `ArraySpec`.
When you try to create a `ActorDistributionNetwork` with python specs, you get an AttributeError: 'tuple' object has no attribute 'num_elements'. The following code replicates the error:

    action_spec = array_spec.BoundedArraySpec((1,), np.float32, minimum=0, maximum=10)  
    observation_spec = array_spec.BoundedArraySpec((5,), np.float32, minimum=-1, maximum=1)
    actor_network = ActorDistributionNetwork(observation_spec, action_spec)
  

However if you change the `action_spec` to a `tensor_spec` it works fine:

    action_spec = array_spec.BoundedArraySpec((1,), np.float32, minimum=0, maximum=10)  
    observation_spec = array_spec.BoundedArraySpec((5,), np.float32, minimum=-1, maximum=1)
    actor_network = ActorDistributionNetwork(observation_spec, tensor_spec.from_spec(action_spec))

The exception is cause be the fact that `type(tensor_spec.from_spec(action_spec).shape) -> <class 'tensorflow.python.framework.tensor_shape.TensorShape'>`  while `type(action_spec.shape) -> <class 'tuple'>` and tuple does have a `num_elements()` functions

However multiple places in the code base assume that shape is an instance of `TensorShape` (often `TensorShape` specific methods such as `.num_elements()`, `.num_elements()`, etc are used).  I think the easiest solution would be to replace `self._shape = tuple(shape)` in the `ArraySpec` constructor with `self._shape = tf.TensorShape(shape)`
I can make a PR if you want.

    
The stack trace of the example code:

    Traceback (most recent call last):
      File "C:/Users/user/Documents/Github/tf_agents_test/tf_agents_test/PyEnvExample.py", line 17, in <module>
        actor_network = ActorDistributionNetwork(observation_spec, action_spec)
      File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\gin\config.py", line 1032, in wrapper
        utils.augment_exception_message_and_reraise(e, err_str)
      File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\gin\utils.py", line 49, in augment_exception_message_and_reraise
        six.raise_from(proxy.with_traceback(exception.__traceback__), None)
      File "<string>", line 3, in raise_from
      File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\gin\config.py", line 1009, in wrapper
        return fn(*new_args, **new_kwargs)
      File "c:\users\user\documents\github\tf_agents_test\tf_agents\tf_agents\networks\network.py", line 89, in _capture_init
        init(self, **kwargs)
      File "c:\users\user\documents\github\tf_agents_test\tf_agents\tf_agents\networks\actor_distribution_network.py", line 145, in __init__
        projection_networks = tf.nest.map_structure(map_proj, output_tensor_spec)
      File "C:\Users\user\Anaconda3\envs\tf_agent\lib\site-packages\tensorflow_core\python\util\nest.py", line 536, in map_structure
        structure[0], [func(*x) for x in entries],
      File "C:\Users\user\Anaconda3\envs\tf_agent\lib\site-packages\tensorflow_core\python\util\nest.py", line 536, in <listcomp>
        structure[0], [func(*x) for x in entries],
      File "c:\users\user\documents\github\tf_agents_test\tf_agents\tf_agents\networks\actor_distribution_network.py", line 143, in map_proj
        return continuous_projection_net(spec)
      File "c:\users\user\documents\github\tf_agents_test\tf_agents\tf_agents\networks\actor_distribution_network.py", line 48, in _normal_projection_net
        scale_distribution=False)
      File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\gin\config.py", line 1032, in wrapper
        utils.augment_exception_message_and_reraise(e, err_str)
      File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\gin\utils.py", line 49, in augment_exception_message_and_reraise
        six.raise_from(proxy.with_traceback(exception.__traceback__), None)
      File "<string>", line 3, in raise_from
      File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\gin\config.py", line 1009, in wrapper
        return fn(*new_args, **new_kwargs)
      File "c:\users\user\documents\github\tf_agents_test\tf_agents\tf_agents\networks\network.py", line 89, in _capture_init
        init(self, **kwargs)
      File "c:\users\user\documents\github\tf_agents_test\tf_agents\tf_agents\networks\normal_projection_network.py", line 102, in __init__
        sample_spec.shape.num_elements(),
    AttributeError: 'tuple' object has no attribute 'num_elements'
      In call to configurable 'NormalProjectionNetwork' (<function NormalProjectionNetwork.__init__ at 0x000001FC21A46488>)
      In call to configurable 'ActorDistributionNetwork' (<function ActorDistributionNetwork.__init__ at 0x000001FC21A46950>)

**Comment by kbanoop** [comment]
Hi, thanks for raising the issue, but for Networks we expect the specs to be TensorSpecs rather than ArraySpecs since the inputs are TF.Tensors rather than arrays. 
https://github.com/tensorflow/agents/blob/e31a1c6dfb744c688deda7a9024bb19631d5bce0/tf_agents/networks/actor_distribution_network.py#L79

Also ArraySpecs are meant to be used with numpy arrays, so the shape should not be a tf.TensorShape.

**Comment by profPlum** [comment]
@kbanoop This doesn't make sense though because a PythonEnvironment will return an ArraySpec for the action spec (tested with gym environment wrapped in gym_wrapper.GymWrapper()).

That implies that they will be valid & yet it appears they are not.
