### ISSUE TITLE
no attribute 'register_symbolic_tensor_type'

### ISSUE THREAD

**Issue by artificial-lshamis** [tensorflow/agents#2]
I'm trying to run the example: `tf_agents/agents/dqn/examples/train_eval_gym.py`

The error I get:
```python
# python3 /usr/local/lib/python3.6/dist-packages/tf_agents/agents/dqn/examples/train_eval_gym.py --root_dir=$HOME/tmp/dqn/gym/cart-pole/ --alsologtostderr
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/agents/dqn/examples/train_eval_gym.py", line 37, in <module>
    from tf_agents.agents.dqn import dqn_agent
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/agents/__init__.py", line 17, in <module>
    from tf_agents.agents.ddpg.ddpg_agent import DdpgAgent
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/agents/ddpg/ddpg_agent.py", line 29, in <module>
    from tf_agents.agents import tf_agent
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/agents/tf_agent.py", line 28, in <module>
    from tf_agents.environments import trajectory
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/environments/trajectory.py", line 28, in <module>
    from tf_agents.environments import time_step as ts
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/environments/time_step.py", line 28, in <module>
    from tf_agents.specs import array_spec
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/specs/__init__.py", line 19, in <module>
    from tf_agents.specs.tensor_spec import BoundedTensorSpec
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/specs/tensor_spec.py", line 24, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/__init__.py", line 78, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/__init__.py", line 25, in <module>
    from tensorflow_probability.python import layers
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/__init__.py", line 30, in <module>
    from tensorflow_probability.python.layers.distribution_layer import CategoricalMixtureOfOneHotCategorical
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/distribution_layer.py", line 46, in <module>
    keras_tf_utils.register_symbolic_tensor_type(
AttributeError: module 'tensorflow.python.keras.utils.tf_utils' has no attribute 'register_symbolic_tensor_type'
```

The runtime environment (as a Dockerfile):
```dockerfile
FROM ubuntu:bionic

RUN apt update && apt install -y python3 python3-pip

RUN pip3 install --upgrade tensorflow tf-agents-nightly
```

**Comment by oars** [comment]
You need to depend on `tf-nightly`.
