### ISSUE TITLE
I get error when creating TFUniformReplayBuffer

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/agents#242]
the call stack when I get the error is shown below.

>Traceback (most recent call last):
  File "baseline1_train.py", line 161, in <module>
    main();
  File "baseline1_train.py", line 103, in main
    max_length = 100000);
  File "/home/xieyi/.local/lib/python3.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/xieyi/.local/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/xieyi/.local/lib/python3.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/xieyi/.local/lib/python3.7/site-packages/tf_agents/replay_buffers/tf_uniform_replay_buffer.py", line 151, in __init__
    self._data_table = table_fn(self._data_spec, self._capacity_value)
  File "/home/xieyi/.local/lib/python3.7/site-packages/tf_agents/replay_buffers/table.py", line 55, in __init__
    self._tensor_spec)
  File "/home/xieyi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 547, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/xieyi/.local/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 547, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/xieyi/.local/lib/python3.7/site-packages/tf_agents/replay_buffers/table.py", line 52, in _create_unique_slot_name
    return tf.compat.v1.get_default_graph().unique_name(spec.name or 'slot')
AttributeError: 'NoneType' object has no attribute 'name'
  In call to configurable 'TFUniformReplayBuffer' (<function TFUniformReplayBuffer.__init__ at 0x7f9b9d480710>)

I dont know if the problem reside in the implement of agent or environment. Is the call stack enough for locating the problem or I can paste more about my code.

**Comment by sguada** [comment]
The error seems to indicate that you didn't pass a TensorSpec when building the replay buffer.

**Comment by breadbread1984** [comment]
yeah it is the problem of output distribution specification of actor network. I use jointdistributionsequential to output a joint distribution of several distributions. it has no input param shape. so I just give None, then I got the error.
what is the right way if I want actor network to generate action from joint distinct distributions.
