### ISSUE TITLE
Driver Loop InvalidArgumentError with batched env + parallel environments

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/agents#256]
Hello team,
I have a custom env that is batched with batch size 1. Everything works fine if no parallel_environments. But now I'm trying to run SAC agent with 2 parallel envs:
by following v2 example: https://github.com/tensorflow/agents/blob/master/tf_agents/agents/sac/examples/v2/train_eval_rnn.py

1) I noticed that if I do:
    num_parallel_environments = 2
    replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
        data_spec=tf_agent.collect_data_spec,
        **batch_size=tf_env.batch_size*num_parallel_environments**,
        max_length=replay_buffer_capacity)

I get a shape  error from replay_buffer._add_batch. 
To overcome this I investigated and discovered that when we wrap env with ParallelPyEnvironment by doing
py_env = parallel_py_environment.ParallelPyEnvironment(
          [lambda: env_load_fn(env_name)]*num_parallel_environments)

tf_env = tf_py_environment.TFPyEnvironment(py_env)

the resulting py_env.batch_size is already equal to the number of num_parallel_environments.
(in my case 2) due ParallelPyEnvironment property and so it is for tf_env too.

( in ParallelPyEnvironment.py)
  @property
  def batch_size(self):
    return self._num_envs

I was able to proceed by doing:

    replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
        data_spec=tf_agent.collect_data_spec,
        **batch_size=tf_env.batch_size**
        max_length=replay_buffer_capacity)

than I created :

observers = [replay_buffer.add_batch] + train_metrics
initial_collect_driver = DynamicEpisodeDriver(tf_env, policy, observers, transition_observers=None, num_episodes=100)
initial_collect_driver.run = common.function(initial_collect_driver.run)

but when I run:
 initial_collect_driver.run()

I get this error:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\workspace\Test-SAC\test_agent.py", line 88, in <module>
    model.__run__()
  File "C:\Users\user\Desktop\workspace\Test-SAC\core\model.py", line 75, in __run__
    FLAGS.warmup_episodes
  File "C:\Users\shock\Desktop\workspace\Test-SAC\core\model.py", line 266, in train
    initial_collect_driver.run()
  File "C:\Users\user\Anaconda3\envs\agents\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\user\Anaconda3\envs\agents\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 641, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\Users\user\Anaconda3\envs\agents\lib\site-packages\tensorflow_core\python\eager\function.py", line 1589, in _filtered_call
    self.captured_inputs)
  File "C:\Users\user\Anaconda3\envs\agents\lib\site-packages\tensorflow_core\python\eager\function.py", line 1670, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\shock\Anaconda3\envs\agents\lib\site-packages\tensorflow_core\python\eager\function.py", line 523, in call
    ctx=ctx)
  File "C:\Users\user\Anaconda3\envs\agents\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Can not squeeze dim[1], expected a dimension of 1, got 2
	 [[{{node driver_loop/body/_1/StatefulPartitionedCall_3/StatefulPartitionedCall/Squeeze}}]] [Op:__inference_run_10151]

Function call stack:
run

my observation_spec is like this

observation_spec = OrderedDict([
            ('camera_1', tensor_spec.TensorSpec(shape=(10,), dtype=tf.float32)),
            ('camera_2', tensor_spec.BoundedTensorSpec(shape=(4,),
                dtype=dtype=tf.float32, minimum=[10,10,10,10], maximum=[0,0,0,0])),

Help really appreciated.

**Comment by sguada** [comment]
One quick question why does your Env has batch_size 1? In general the PythonEnv don't have batch dimension and tf_py_environment.TFPyEnvironment will add it.
