### ISSUE TITLE
Breaking of episodic replay buffer on tf-nightly

### ISSUE THREAD

**Issue by mjlbach** [tensorflow/agents#298]
See https://github.com/tensorflow/tensorflow/issues/36418

Reproduction:
```
import tensorflow as tf
import numpy as np

from tf_agents import specs
from tf_agents.replay_buffers import episodic_replay_buffer


class EpisodicReplayBuffer:
    def __init__(self, example_len, buffer_size):
        self.example_len = example_len
        self.buffer_size = buffer_size

        self.episodes_collected = 0

    def initialize(self, episode):
        spec = dict()
        for key, value in episode.items():
            dtype = str(value.dtype)
            if dtype == "int32":
                dtype = tf.int32
            elif dtype == "int64":
                dtype = tf.int64
            elif dtype == "float32":
                dtype = tf.float32
            elif dtype == "float64":
                dtype = tf.float64
            elif dtype == "bool":
                dtype = tf.bool
            else:
                print("Unknown dtype: {}".format(dtype))
                quit()
            shape = list(value.shape)[2:]
            spec[key] = specs.TensorSpec(shape, dtype, key)

        self.replay_buffer = episodic_replay_buffer.EpisodicReplayBuffer(
            spec,
            capacity=self.buffer_size,
            begin_episode_fn=lambda _: False,
            end_episode_fn=lambda _: True,
        )
        # self.add_episode(episode)

    def add_episode(self, episode):
        print("Episode collected: {}\n".format(self.episodes_collected))
        self.episodes_collected += 1
        episode_id = self.replay_buffer.create_episode_ids(num_episodes=0)
        episode = tf.nest.map_structure(lambda v: v[0], episode)
        self.replay_buffer.add_sequence(episode, episode_id)

    def as_dataset(self, batch_size):
        return self.replay_buffer._as_dataset(
            num_steps=self.example_len, sample_batch_size=batch_size
        )


def main():
    strategy = tf.distribute.MirroredStrategy()
    replay_buffer = EpisodicReplayBuffer(4, 4)
    episode = {}
    for key in ["tensor_1", "tensor_2", "tensor_3"]:
        value = np.ones(shape=[1, 4, 4, 4], dtype=np.float32)
        episode[key] = value

    replay_buffer.initialize(episode)
    with strategy.scope():
        replay_buffer.add_episode(episode)
        replay_buffer.add_episode(episode)
        replay_buffer.add_episode(episode)
        dataset = replay_buffer.as_dataset(4)
        distributed_dataset = strategy.experimental_distribute_dataset(dataset)
        iterator = iter(distributed_dataset)
        data = next(iterator)
        print(data)

if __name__ == "__main__":
    main()
```

Also of note, if you move the initialization of the replay buffer under the distributed strategy scope, you get the following error:
```
Traceback (most recent call last):
  File "agents.py", line 76, in <module>
    main()
  File "agents.py", line 66, in main
    replay_buffer.add_episode(episode)
  File "agents.py", line 48, in add_episode
    self.replay_buffer.add_sequence(episode, episode_id)
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tf_agents/replay_buffers/episodic_replay_buffer.py", line 362, in add_sequence
    episode_id, begin_episode, end_episode)
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tf_agents/replay_buffers/episodic_replay_buffer.py", line 995, in _get_episode_id
    name='get_episode_id')
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1392, in cond_for_tf_v2
    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1205, in cond
    result = true_fn()
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tf_agents/replay_buffers/episodic_replay_buffer.py", line 980, in _get_new_episode_id
    return self._add_episode_critical_section.execute(_assign_new_episode_id)
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tensorflow_core/python/ops/critical_section_ops.py", line 284, in execute
    r = fn()
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tf_agents/replay_buffers/episodic_replay_buffer.py", line 968, in _assign_new_episode_id
    self._episodes_loc_to_id_map, episode_location, new_episode_id)
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tensorflow_core/python/ops/state_ops.py", line 304, in scatter_update
    return ref._lazy_read(gen_resource_variable_ops.resource_scatter_update(  # pylint: disable=protected-access
  File "/home/mjlbach/.virtualenvs/poetry3.7/lib/python3.7/site-packages/tensorflow_core/python/distribute/values.py", line 144, in __getattr__
    return getattr(self.get(), name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_lazy_read'
```

**Comment by mjlbach** [comment]
I believe this is fixed on the latest nightly, however, initializing the episodic replay buffer under a distributed strategy still elicits the second error above.

**Comment by leroidauphin** [comment]
The linked pull request appears to fix the parts of TF-Agents code which contribute to this issue. Having applied that patch, it appears that the TensorFlow `MirroredVariable` still needs to be updated to support `sparse_read` before this issue has been addressed.

**Comment by ebrevdo** [comment]
+Katya Gonina <kgonina@google.com> +Anjali Sridhar
<anjalisridhar@google.com>

**Comment by egonina** [comment]
@anj-s do you know if sparse_read will be updated in MirroredVariable soon?

**Comment by egonina** [comment]
any updates on this issue? can we link a TF issue here that is blocking this? @anj-s

**Comment by anj-s** [comment]
@egonina Not yet. I'll look into this and have an update soon. Thanks!

**Comment by ebrevdo** [comment]
We're deprecating EpisodicReplayBuffer for Reverb replay buffer, which honestly is much easier to work with and has better features (and easier to debug when it breaks!).  So not sure if this has been fixed, but I'll mark as obsolete. Please reopen if this is a legacy issue that's still biting you.
