### ISSUE TITLE
utils.validate_py_environment() does not support environments with batched actions

### ISSUE THREAD

**Issue by karishnu** [tensorflow/agents#309]
validate_py_environment should send multiple batched actions when validating an environment with batched as True.

**Comment by pierceChinaGfw** [comment]
Yes, I also found the same bug.

My testing code is here:
```
def testValidateWithBatchSize():
	batchSize = 2
	obsSpec = array_spec.BoundedArraySpec((2, 3), np.int32, -10, 10)
	env = random_py_environment.RandomPyEnvironment(obsSpec, batch_size=batchSize)
	validate_py_environment(env)

```
The error log is here:
```
>>> testValidateWithBatchSize()
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "<console>", line 5, in testValidateWithBatchSize
  File "/usr/local/lib/python3.6/dist-packages/tf_agents/environments/utils.py", line 60, in validate_py_environment
    (time_step, time_step_spec))
ValueError: Given `time_step`: TimeStep(step_type=array([0, 0], dtype=int32), reward=array([0., 0.], dtype=float32), discount=array([1., 1.], dtype=float32), observation=array([[[-4,  9,  4],
        [ 0, -3, 10]],

       [[-4,  8,  0],
        [ 0, 10, -7]]], dtype=int32)) does not match expected `time_step_spec`: TimeStep(step_type=ArraySpec(shape=(), dtype=dtype('int32'), name='step_type'), reward=ArraySpec(shape=(), dtype=dtype('float32'), name='reward'), discount=BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0), observation=BoundedArraySpec(shape=(2, 3), dtype=dtype('int32'), name=None, minimum=-10, maximum=10))

```

**Comment by pierceChinaGfw** [comment]
The following test codes without batchSize works fine
```
    def testValidateWithoutBatchSize(self):
        batchSize = None
        obsSpec = array_spec.BoundedArraySpec((2, 3), np.int32, -10, 10)
        env = random_py_environment.RandomPyEnvironment(obsSpec, batch_size=batchSize)
        validate_py_environment(env)

```

**Comment by ebrevdo** [comment]
@kbanoop this should be easy to fix.
