### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_agents.bandits.specs'

### ISSUE THREAD

**Issue by fredcallaway** [tensorflow/agents#341]
I get this error importing tf_agents.environment in a fresh install.

### Full stack trace
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/tfa/lib/python3.7/site-packages/tf_agents/environments/__init__.py", line 26, in <module>
    from tf_agents.environments import utils
  File "/home/ubuntu/miniconda3/envs/tfa/lib/python3.7/site-packages/tf_agents/environments/utils.py", line 25, in <module>
    from tf_agents.policies import random_py_policy
  File "/home/ubuntu/miniconda3/envs/tfa/lib/python3.7/site-packages/tf_agents/policies/__init__.py", line 20, in <module>
    from tf_agents.policies import epsilon_greedy_policy
  File "/home/ubuntu/miniconda3/envs/tfa/lib/python3.7/site-packages/tf_agents/policies/epsilon_greedy_policy.py", line 29, in <module>
    from tf_agents.bandits.policies import policy_utilities
  File "/home/ubuntu/miniconda3/envs/tfa/lib/python3.7/site-packages/tf_agents/bandits/policies/__init__.py", line 19, in <module>
    from tf_agents.bandits.policies import greedy_reward_prediction_policy
  File "/home/ubuntu/miniconda3/envs/tfa/lib/python3.7/site-packages/tf_agents/bandits/policies/greedy_reward_prediction_policy.py", line 28, in <module>
    from tf_agents.bandits.specs import utils as bandit_spec_utils
ModuleNotFoundError: No module named 'tf_agents.bandits.specs'
```

### Replication steps
```
conda create -n test python=3.7
conda activate test
pip install tf-nightly
pip install tf-agents-nightly
python -c 'import tf_agents.environments'
```

**Comment by bartokg** [comment]
Could you please try again? The __init__ should be fixed now.

**Comment by summer-yue** [comment]
I verified that this was fixed. Closing this issue. Thanks Fred for reporting and thanks Gabor for the  fix!
