### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'rank'

### ISSUE THREAD

**Issue by AndreyBulezyuk** [tensorflow/agents#363]
Trying out the most basic example on 

- Windows 10
- Python 3.7
- tensorflow 2.1.0
- tf-agents 0.4.0

Error i get
```
Traceback (most recent call last):
  File "src\agent.py", line 58, in <module>
    action, _states = agent.policy.action(obs)
  File "C:\Users\andre\.virtualenvs\ZeusTrader\lib\site-packages\tf_agents\policies\tf_policy.py", line 279, in action
    step = action_fn(time_step=time_step, policy_state=policy_state, seed=seed)
  File "C:\Users\andre\.virtualenvs\ZeusTrader\lib\site-packages\tf_agents\utils\common.py", line 154, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "C:\Users\andre\.virtualenvs\ZeusTrader\lib\site-packages\tf_agents\policies\random_tf_policy.py", line 89, in _action
    outer_dims = nest_utils.get_outer_shape(time_step, self._time_step_spec)
  File "C:\Users\andre\.virtualenvs\ZeusTrader\lib\site-packages\tf_agents\utils\nest_utils.py", line 394, in get_outer_shape
    nested_tensor, spec, num_outer_dims=num_outer_dims):
  File "C:\Users\andre\.virtualenvs\ZeusTrader\lib\site-packages\tf_agents\utils\nest_utils.py", line 97, in is_batched_nested_tensors
    if any(spec_shape.rank is None for spec_shape in spec_shapes):
  File "C:\Users\andre\.virtualenvs\ZeusTrader\lib\site-packages\tf_agents\utils\nest_utils.py", line 97, in <genexpr>
    if any(spec_shape.rank is None for spec_shape in spec_shapes):
AttributeError: 'tuple' object has no attribute 'rank'

```

Code i run
```
import tensorflow as tf
from collections import Counter, defaultdict
from tf_agents.networks import q_network
from tf_agents.utils import common
from tf_agents.agents.dqn import dqn_agent
from tf_agents.agents.random.random_agent import RandomAgent
from tf_agents.environments import suite_gym
from environment import StockExchangeEnv01

# tried with and without..error persists
# tf.compat.v1.enable_v2_behavior()

learning_rate = 0.0001
optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)

# tried both my own Environment and the basic "cartpole-v0"
train_env = StockExchangeEnv01()
env_name = 'CartPole-v0'
#train_env = suite_gym.load(env_name)

train_env.reset()
print(train_env.action_spec())
"""
# Neural Net of the Agent. This NN will get x (env) and spit out y (action).
q_net = q_network.QNetwork(
  train_env.observation_spec(),
  train_env.action_spec(),
  fc_layer_params=(100,))
print(train_env.action_spec())

#
agent = dqn_agent.DqnAgent(
  train_env.time_step_spec(),
  train_env.action_spec(),
  q_network=q_net,
  optimizer=optimizer)
"""

# tried both..dqn agent and random agent

agent = RandomAgent(
    train_env.time_step_spec(),
    train_env.action_spec()
)
agent.initialize()

obs = train_env.reset()
actions = Counter()
pnl = defaultdict(float)
total_rewards = 0.0

for i in range(300):
    #action, _states = model.predict(obs)
    action, _states = agent.policy.action(obs)
    obs, rewards, dones, info = train_env.step(action)
    actions[action[0].item()] += 1
    pnl[action[0].item()] += rewards
    total_rewards += rewards
    if dones:
        break

print('actions : {}'.format(actions))
print('rewards : {}'.format(total_rewards))

```

The code in tf agents gets the 'shape' from the action_spec, which is a tuple in my case. Then it tries to retrieve key "rank" from a tuple. 

What am i missing?

**Comment by summer-yue** [comment]
From your error message, it looks like it's actually failing at "get_outer_shape(time_step, self._time_step_spec)" - when it was trying to get the rank for the time steps.

Could you print `train_env.time_step_spec()` and `obs` and verify that they match?

**Comment by AndreyBulezyuk** [comment]
The prints:

```
action_spec: BoundedTensorSpec(shape=(2, 0), dtype=tf.float32, name=None, minimum=array(-1., dtype=float32), maximum=array(3., dtype=float32))
time_spec: TimeStep(step_type=ArraySpec(shape=(), dtype=dtype('int32'), name='step_type'), reward=ArraySpec(shape=(), dtype=dtype('float32'), name='reward'), discount=BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximu
m=1.0), observation=BoundedArraySpec(shape=(1, 0), dtype=dtype('int32'), name='observation', minimum=0, maximum=2147483647))
2020-05-05 15:32:19.651059: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-05-05 15:32:19.657231: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-05-05 15:32:19.666545: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-IRIRGLF
2020-05-05 15:32:19.671891: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-IRIRGLF
2020-05-05 15:32:19.678403: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
obs: TimeStep(step_type=array(0), reward=array(0., dtype=float32), discount=array(1., dtype=float32), observation=array([0]))
type obs: <class 'tf_agents.trajectories.time_step.TimeStep'>

```

**Comment by summer-yue** [comment]
Looks like a bug. Simple repo:

```
from tf_agents.environments import suite_gym
from tf_agents.utils import nest_utils

train_env = suite_gym.load('CartPole-v0')
time_step = train_env.reset()
print(obs)
print(train_env.time_step_spec())
nest_utils.get_outer_shape(obs, train_env.time_step_spec())
```

Eugene, could you please take a look?

**Comment by TomLouisKeller** [comment]
I had a similar problem, that the method `_check_action_spec()` located in `agents/dqn/dqn_agents.py`  on line 264 threw the same error ('tuple' object has no attribute 'rank').

I was able to fix it by wrapping a Python Environment in TensorFlow like this:
```
from tf_agents.environments import tf_py_environment
environment = tf_py_environment.TFPyEnvironment(environment)
```

Hope this can help those who look for a quick fix.

**Comment by ebrevdo** [comment]
Thanks for the repro!  Will look at fixing this.

**Comment by AndreyBulezyuk** [comment]
Thanks @TomLouisKeller ,
now getting another Exception, which seems to be unrelated to the current issue.

**Comment by CoandaEffect** [comment]
Getting the same error running on WSL Ubuntu, same versions as OP. I only get the error if Python Environment is not wrapped. @TomLouisKeller recommendation will work if no specific need for the Python Environment.

To verify, is DqnAgent intended to work with Python Environments or must one wrap in TensorFlow?

**Comment by vlaskinvlad** [comment]
I got the same error while implementing pure TF-env without python wrappers.

**Comment by sguada** [comment]
Could you verify that the specs of the environment use TensorSpecs?

**Comment by RunningDongxu** [comment]
I got the same error while using the tensorflow2.2 on a ubuntu system, but no problem if using the TensorFlow 1.14

**Comment by elliotwoods** [comment]
Any notes on what to do if you're not using a gym environment?
e.g. this complains with the `'tuple' object has no attribute 'rank'` error:

```python
self.observation_spec = ArraySpec((options['state_dimensions'],), np.dtype('float32'), 'observation')
self.reward_spec = ArraySpec((1,), np.dtype('float32'), 'reward')
self.action_spec = BoundedArraySpec((1,), np.dtype('int32'), minimum=-1, maximum=1, name='action')
self.time_step_spec = time_step.time_step_spec(self.observation_spec)

self.optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=options['learning_rate'])
self.q_network = q_network.QNetwork(self.observation_spec, self.action_spec, fc_layer_params=options['fc_layer_params'])
self.agent = dqn_agent.DqnAgent(self.time_step_spec, self.action_spec
	, q_network = self.q_network
	, optimizer = self.optimizer
	, td_errors_loss_fn = common.element_wise_squared_loss
	, epsilon_greedy = 0.1
	, gamma = 0.9)
```

**Comment by elliotwoods** [comment]
Fixed it.. need to use `TensorSpec` and `BoundedTensorSpec` instead of `ArraySpec`, e.g.:

```python
self.observation_spec = TensorSpec((options['state_dimensions'],), np.dtype('float32'), 'observation')
self.reward_spec = TensorSpec((1,), np.dtype('float32'), 'reward')
self.action_spec = BoundedTensorSpec((1,), np.dtype('int32'), minimum=0, maximum=2, name='action')
self.time_step_spec = time_step.time_step_spec(self.observation_spec)

self.optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=options['learning_rate'])
self.q_network = q_network.QNetwork(self.observation_spec, self.action_spec, fc_layer_params=options['fc_layer_params'])
self.agent = dqn_agent.DqnAgent(self.time_step_spec, self.action_spec
	, q_network = self.q_network
	, optimizer = self.optimizer
	, td_errors_loss_fn = common.element_wise_squared_loss
	, epsilon_greedy = 0.1
	, gamma = 0.9)
```

**Comment by ebrevdo** [comment]
I hope to unify TensorSpec and ArraySpec under the same object this week.  For now you can convert env specs to tensor specs using [from_spec](https://www.tensorflow.org/agents/api_docs/python/tf_agents/specs/tensor_spec/from_spec).

**Comment by ebrevdo** [comment]
I wasn't quite able to unify the two, but I made the agents try to auto-convert from ArraySpec to TensorSpec whenever possible.  This code still hits errors though so I'll add some additional fixes specific to DQN.

**Comment by dontlooksoworried** [comment]
> Fixed it.. need to use `TensorSpec` and `BoundedTensorSpec` instead of `ArraySpec`, e.g.:
> 
> ```python
> self.observation_spec = TensorSpec((options['state_dimensions'],), np.dtype('float32'), 'observation')
> self.reward_spec = TensorSpec((1,), np.dtype('float32'), 'reward')
> self.action_spec = BoundedTensorSpec((1,), np.dtype('int32'), minimum=0, maximum=2, name='action')
> self.time_step_spec = time_step.time_step_spec(self.observation_spec)
> 
> self.optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=options['learning_rate'])
> self.q_network = q_network.QNetwork(self.observation_spec, self.action_spec, fc_layer_params=options['fc_layer_params'])
> self.agent = dqn_agent.DqnAgent(self.time_step_spec, self.action_spec
> 	, q_network = self.q_network
> 	, optimizer = self.optimizer
> 	, td_errors_loss_fn = common.element_wise_squared_loss
> 	, epsilon_greedy = 0.1
> 	, gamma = 0.9)
> ```

Saved me a bunch of time, I was stuck on the same thing. Appreciate you commenting!
