### ISSUE TITLE
TensorFlow 2.2 Support.

### ISSUE THREAD

**Issue by tfboyd** [tensorflow/agents#367]
I will update this issue until TF-Agents 0.5.0 is the stable release.

TensorFlow 2.2 was released on 07-MAY. The current TF-Agents 0.4.0 should work with TensorFlow 2.2. While testing the [0.4.0 branch](https://github.com/tensorflow/agents/tree/r0.4.0), I found that a single unit test fails for a bandits unit test but it is a value comparison that may be based on some change to random seed. I did not look into it at all. The exact error is at the bottom of this comment. No other unit test fail. 

**TF-Agents 0.5.0** will be the release that is tested against TF 2.2 and this is the timeline

- [DONE] [Cut the branch](https://github.com/tensorflow/agents/tree/r0.5.0) at a point where all tests pass
- [DONE] Build and push the RC0 to `pypi pip install tf-agents==0.5.0rc0`
- [15-MAY] Make the RC the stable version and default when running pip install tf-agents

Error when running 0.4.0 test against TF 2.2, this does not seem to be fatal and may be a failure of the test. This will not be resolved and the suggestion will be to use TF-Agents 0.5.0 with TensorFlow 2.2.

```
FAIL: testObservationAndRewardsVary_observation_[5]action[3]_batch_1 (bandits.environments.piecewise_stochastic_environment_test.PiecewiseStochasticEnvironmentTest)
testObservationAndRewardsVary_observation_[5]action[3]_batch_1 (bandits.environments.piecewise_stochastic_environment_test.PiecewiseStochasticEnvironmentTest)
testObservationAndRewardsVary_observation_[5]action[3]_batch_1(observation_shape=[5], action_shape=[3], batch_size=1, seed=12345)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.VOLdIEhk5W/virtualenv/3.6.1/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 1109, in decorated
    f(self, *args, **kwargs)
  File "/tmp/tmp.VOLdIEhk5W/virtualenv/3.6.1/lib/python3.6/site-packages/absl/testing/parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "/workspace/tf_agents/bandits/environments/piecewise_stochastic_environment_test.py", line 128, in testObservationAndRewardsVary
    observation_to_reward_samples[int(t)])
  File "/tmp/tmp.VOLdIEhk5W/virtualenv/3.6.1/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 1151, in decorated
    return f(*args, **kwds)
  File "/tmp/tmp.VOLdIEhk5W/virtualenv/3.6.1/lib/python3.6/site-packages/tensorflow/python/framework/test_util.py", line 2563, in assertNotAllClose
    raise AssertionError("The two values are close at all elements")
AssertionError: The two values are close at all elements

======================================================================================
Tests run: 1884 grouped and 4 external.  Errors: 0  Failures: 1  External failures: 0.
======================================================================================
```

*  Edit (13-MAY): RC0 was pushed to pypi and the task list updated.

**Comment by tfboyd** [comment]
TF-Agents 0.5.0 was released as was 0.6.0.  I forgot to close this.
