### ISSUE TITLE
Model Hangs Indefinitely with ParallelPyEnvironment

### ISSUE THREAD

**Issue by mcmah309** [tensorflow/agents#433]
My model can run correctly with 
```
train_py_env = RegexEnv(max_line_length)
eval_py_env = RegexEnv(max_line_length)
train_env=tf_py_environment.TFPyEnvironment(train_py_env)
eval_env = tf_py_environment.TFPyEnvironment(eval_py_env)
```
But when I change it to this
```
parallel_train_py=parallel_py_environment.ParallelPyEnvironment([RegexEnv(max_line_length) for _ in range(3)])
parallel_eval_py=parallel_py_environment.ParallelPyEnvironment([RegexEnv(max_line_length) for _ in range(3)])
train_env=tf_py_environment.TFPyEnvironment(parallel_train_py)
eval_env = tf_py_environment.TFPyEnvironment(parallel_eval_py)
```
The program hangs here forever with this output
```
2020-07-23 15:17:32.030460: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-23 15:17:32.033216: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
_
```
When I use CTRL-C I get this
```
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "regexpar.py", line 188, in <module>
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    parallel_train_py=parallel_py_environment.ParallelPyEnvironment([RegexEnv] *30)
    exitcode = _main(fd)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\gin\config.py", line 1009, in wrapper
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 113, in _main
    preparation_data = reduction.pickle.load(from_parent)
    return fn(*new_args, **new_kwargs)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 70, in __init__
KeyboardInterrupt
    self.start()
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 84, in start
    env.start(wait_to_start=self._start_serially)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 224, in start
    self._process.start()
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 265, in __getattr__
    return self._receive()
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 334, in _receive
    message, payload = self._conn.recv()
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\connection.py", line 306, in _recv_bytes
    [ov.event], False, INFINITE)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 290, in close
    self._process.join(5)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 139, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
```
The last calls changes when I exit the program. This makes me think there is an error in tensorflow which makes it get stuck. Here's what I mean from another run.
```
Traceback (most recent call last):
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\site-packages\tf_agents\environments\parallel_py_environment.py", line 290, in close
    self._process.join(5)
  File "C:\Users\Dillon\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 139, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
```
I've also tried all the following
```
parallel_py_environment.ParallelPyEnvironment([RegexEnv() for _ in range(3)])
parallel_py_environment.ParallelPyEnvironment([[RegexEnv] for _ in range(3)])
parallel_py_environment.ParallelPyEnvironment([RegexEnv] * 3)
```
max_line_length is an optional int for my env. I've tried hard coding it as well. Any suggestions would help

**Comment by sguada** [comment]
You need to pass a list of callables to `parallel_py_environment.ParallelPyEnvironment()`

**Comment by mcmah309** [comment]
I did that in the examples of what I tried at the bottom and I still have the same problem

**Comment by coolvinay1903** [comment]
I am also stuck with the same problem. @mcmah309 were you able to find a work-around for this?

**Comment by mcmah309** [comment]
@coolvinay1903 I was not. The project as it relates to Tensorflow was cancelled due to this issue. I recommend @sguada that the Tensorflow team take another look at this.

**Comment by ebrevdo** [comment]
We need to see how you call main.  Can you include your __main__ code?

**Comment by tfboyd** [comment]
Closing due to age and lack of recent activity. If the issue still exists, please open a new issue and reference this one.
