### ISSUE TITLE
input shape for RnnNetworks

### ISSUE THREAD

**Issue by Bonkersplonk** [tensorflow/agents#575]
I have an environment that produces frames of shape (100, 150, 1) (grayscale). After wrapping my environment with the HistoryWrapper, the final output shape is (3, 100, 150, 1).

From what I've seen, when creating the variables for the network, an input is randomly sampled using the input_tensor_spec after adding a batch dimension with a value of 1, and before feeding to the lstm layer, a time dimension is added if the number of outer dims is not 2 (which it will never not be, as the shape of the random_input is compared to the input_tensor_spec which only lacks the batch dimension). Also, the encoding network squashes the time dimension and the batch dimension into one so that the shape is correct for the EncodingNetwork's forward pass. So I would assume that I'm not supposed to put the time dimension in the input_tensor_spec, so that the LSTMEncodingNetwork's forward pass doesn't add an extra time dimension.

However, if I don't add the time dimension. the unstacked reset_mask_ta TensorArray only has a size of 1, which gives me an OutOfRangeErro(Tried to read from index 1 but array size is: 1) when I try to run the network on an actual input from my environment in the _dynamic_unroll_multi_step function.

So what should be the proper way of defining the input_tensor_spec for RnnNetworks?

**Comment by ebrevdo** [comment]
Just so I understand correctly, are you passing tensors shaped `[B, T, 3, 100, 150, 1]` directly to the network without doing any preprocessing?  If so, LSTMs do not know how to handle this.  One option is to perform an inner reshape in a `preprocessing_layer`, specifically you can use `tf_agents.keras_layers.InnerReshape(current_shape=[None]*3, new_shape=[-1])` to bring the tensors to shape `[B, T, 3*100*150]`.  However, you may find you want to do other forms of preprocessing (like running through an pretrained resnet) given you're handling images.

Please reopen if that doesn't resolve your issue and we'll be happy to continue debugging!  In that case, please provide a simple repro and your failing stack trace.

**Comment by Bonkersplonk** [comment]
Hey, thanks for the reply. Actually, 3 is number of time steps, so the shape is `[B, T, 100, 150, 1]` where `T = 3`. The environment actually generates images of shape `[100, 150]` which I expand to `[100, 150, 1]` using a preprocessing layer.

Here is my code:
```
import functools
import time
import tf_agents
import gym
import gym_chrome_dino
import numpy as np
import tensorflow as tf

from absl import app, flags, logging
from gym.wrappers import GrayScaleObservation, ResizeObservation, TransformObservation, FrameStack
from tf_agents.environments import suite_gym, tf_py_environment, parallel_py_environment, wrappers
from tf_agents.metrics import tf_metrics
from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.utils import common
from tf_agents.eval import metric_utils
from tf_agents.policies import policy_saver
from tf_agents.drivers import dynamic_episode_driver
from tf_agents.system import system_multiprocessing as multiprocessing

flags.DEFINE_integer('buffer_capacity', 10000, 'Replay buffer capacity')
flags.DEFINE_integer('eval_episodes', 30, 'Number of eval episodes')
flags.DEFINE_integer('summary_frequency', 50, 'Interval to log summaries')
flags.DEFINE_integer('num_envs', 30, 'Number of parallel environments for training')
flags.DEFINE_integer('epochs', 25, 'Number of epochs')
flags.DEFINE_integer('collect_episodes', 30, 'Number of collect episodes per iteration')
flags.DEFINE_integer('num_env_steps', 25000000, 'Number of env steps to run')
flags.DEFINE_integer('eval_frequency', 500, 'Interval to run eval')
flags.DEFINE_integer('log_frequency', 50, 'Interval to log')
flags.DEFINE_integer('train_save_frequency', 500, 'Interval to save the agent')
flags.DEFINE_integer('policy_save_frequency', 500, 'Interval to save the policy')

FLAGS = flags.FLAGS


def create_env(name, grayscale=False, shape=None, transform_fn=None):
    env = gym.make(name)

    if grayscale:
        env = GrayScaleObservation(env)

    if shape is not None:
        env = ResizeObservation(env, shape)

    if transform_fn is not None:
        env = TransformObservation(env, transform_fn)

    env = suite_gym.wrap_env(env)
    env = wrappers.HistoryWrapper(env, 3)
    return env


def main(_):
    tf.compat.v1.enable_v2_behavior()
    tf.config.experimental.set_memory_growth(tf.config.list_physical_devices('GPU')[0], True)

    train_summary_writer = tf.summary.create_file_writer('logs/train', flush_millis=1000)
    train_summary_writer.set_as_default()

    eval_summary_writer = tf.summary.create_file_writer('logs/eval', flush_millis=1000)
    eval_metrics = [
        tf_metrics.AverageReturnMetric(buffer_size=FLAGS.eval_episodes),
        tf_metrics.AverageEpisodeLengthMetric(buffer_size=FLAGS.eval_episodes),
        tf_metrics.MaxReturnMetric(buffer_size=FLAGS.eval_episodes)
    ]

    global_step = tf.compat.v1.train.get_or_create_global_step()

    with tf.summary.record_if(lambda: tf.equal(global_step % FLAGS.summary_frequency, 0)):
        eval_env = tf_py_environment.TFPyEnvironment(create_env(
            'ChromeDino-v0',
            grayscale=True,
            shape=(100, 150),
            transform_fn=lambda x: np.squeeze(x)
        ))
        env = tf_py_environment.TFPyEnvironment(parallel_py_environment.ParallelPyEnvironment(
            [lambda: create_env(
                'ChromeDino-v0',
                grayscale=True,
                shape=(100, 150),
                transform_fn=lambda x: np.squeeze(x)
            )] * FLAGS.num_envs)
        )

        observation_spec = env.observation_spec()
        observation_spec = tf_agents.specs.BoundedTensorSpec(
            shape=(3, 100, 150),
            dtype=tf.float32,
            minimum=observation_spec.minimum,
            maximum=observation_spec.maximum,
            name=observation_spec.name
        )
        action_spec = env.action_spec()
        time_step_spec = env.time_step_spec()
        time_step_spec._replace(observation=observation_spec)

        conv_layer_params = [(16, 3, 2), (32, 3, 1)]
        input_fc_layer_params = [128]
        lstm_size = (64,)
        output_fc_layers_params = [32]

        actor_net = tf_agents.networks.actor_distribution_rnn_network.ActorDistributionRnnNetwork(
            input_tensor_spec=observation_spec,
            output_tensor_spec=action_spec,
            preprocessing_layers=tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, -1)),
            conv_layer_params=conv_layer_params,
            input_fc_layer_params=input_fc_layer_params,
            lstm_size=lstm_size,
            output_fc_layer_params=output_fc_layers_params
        )

        value_net = tf_agents.networks.value_rnn_network.ValueRnnNetwork(
            input_tensor_spec=observation_spec,
            preprocessing_layers=tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, -1)),
            conv_layer_params=conv_layer_params,
            input_fc_layer_params=input_fc_layer_params,
            lstm_size=lstm_size
        )

        agent = tf_agents.agents.PPOAgent(
            time_step_spec=time_step_spec,
            action_spec=action_spec,
            optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
            actor_net=actor_net,
            value_net=value_net,
            importance_ratio_clipping=0.2,
            use_gae=True,
            normalize_rewards=False,
            num_epochs=FLAGS.epochs,
            train_step_counter=global_step
        )

        agent.initialize()

        environment_steps_metric = tf_metrics.EnvironmentSteps()
        step_metrics = [
            tf_metrics.NumberOfEpisodes(),
            environment_steps_metric
        ]
        train_metrics = [
            *step_metrics,
            tf_metrics.AverageReturnMetric(buffer_size=FLAGS.num_envs),
            tf_metrics.AverageEpisodeLengthMetric(buffer_size=FLAGS.num_envs)
        ]

        eval_policy = agent.policy
        collect_policy = agent.collect_policy

        buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
            data_spec=agent.collect_data_spec,
            batch_size=FLAGS.num_envs,
            max_length=FLAGS.buffer_capacity
        )

        train_checkpointer = common.Checkpointer(
            ckpt_dir='train',
            agent=agent,
            global_step=global_step,
            metrics=metric_utils.MetricsGroup(train_metrics, 'train_metrics')
        )

        policy_checkpointer = common.Checkpointer(
            ckpt_dir='train/policy',
            policy=eval_policy,
            global_step=global_step
        )

        saved_model = policy_saver.PolicySaver(
            policy=eval_policy,
            train_step=global_step
        )

        train_checkpointer.initialize_or_restore()

        collect_driver = dynamic_episode_driver.DynamicEpisodeDriver(
            env=env,
            policy=collect_policy,
            observers=[buffer.add_batch] + train_metrics,
            num_episodes=FLAGS.collect_episodes
        )

        def train_step():
            trajectories = buffer.gather_all()
            return agent.train(experience=trajectories)

        collect_driver.run = common.function(collect_driver.run, autograph=False)
        agent.train = common.function(agent.train, autograph=False)
        train_step = common.function(train_step)

        collect_time = 0
        train_time = 0
        timed_at_step = global_step.numpy()

        while environment_steps_metric.result() < FLAGS.num_env_steps:
            global_step_val = global_step.numpy()

            if global_step_val % FLAGS.eval_frequency == 0:
                metric_utils.eager_compute(
                    metrics=eval_metrics,
                    environment=eval_env,
                    policy=eval_policy,
                    num_episodes=FLAGS.eval_episodes,
                    train_step=global_step,
                    summary_writer=eval_summary_writer,
                    summary_prefix='Metrics',
                    use_function=False
                )

            start_time = time.time()
            collect_driver.run()
            collect_time += time.time() - start_time

            start_time = time.time()
            total_loss, _ = train_step()
            buffer.clear()
            train_time += time.time() - start_time

            for metric in train_metrics:
                metric.tf_summaries(
                    train_step=global_step,
                    step_metrics=step_metrics
                )

            if global_step_val % FLAGS.log_frequency == 0:
                logging.info('step = %d, loss = %f', global_step_val, total_loss)
                steps_per_sec = ((global_step_val - timed_at_step) / (collect_time + train_time))
                logging.info('%.3f steps/sec', steps_per_sec)
                logging.info('collect_time = %.3f, train_time = %.3f', collect_time, train_time)

                with tf.summary.record_if(True):
                    tf.summary.scalar(name='global_steps_per_sec', data=steps_per_sec, step=global_step)

                if global_step_val % FLAGS.train_save_frequency:
                    train_checkpointer.save(global_step)

                if global_step_val % FLAGS.policy_save_frequency:
                    policy_checkpointer.save(global_step)
                    saved_model.save('saved_models/ppo/policy_' + ('%d' % global_step_val).zfill(9))

                timed_at_step = global_step_val
                collect_time = 0
                train_time = 0

        metric_utils.eager_compute(
            metrics=eval_metrics,
            environment=eval_env,
            policy=eval_policy,
            num_episodes=FLAGS.eval_episodes,
            train_step=global_step,
            summary_writer=eval_summary_writer,
            summary_prefix='Metrics',
            use_function=False
        )


if __name__ == '__main__':
    multiprocessing.handle_main(functools.partial(app.run, main))
```

With `T = 3`, I expect the input to the lstm to be of shape `[B, 3, 128]`. If the shape set in observation_spec is `[100, 150]`, The `random_input` sampled for variable creation has a shape of `[1, 100, 150, 1]` after preprocessing, and the call method of the LSTMEncodingNetwork adds a time dimension, making the shape `[1, 1, 100, 150, 1]`. This works fine for the call method of both LSTMEncodingNetwork and EncodingNetwork. However, upon receiving a batch of actual data, the run fails with the following traceback:

```
Traceback (most recent call last):
  File "C:/Users/kkhanna/Desktop/nano_control/run_tf_agents.py", line 256, in <module>
    multiprocessing.handle_main(functools.partial(app.run, main))
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\system\default\multiprocessing_core.py", line 78, in handle_main
    return app.run(parent_main_fn, *args, **kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:/Users/kkhanna/Desktop/nano_control/run_tf_agents.py", line 205, in main
    use_function=False
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\gin\config.py", line 1069, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\gin\utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\gin\config.py", line 1046, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\eval\metric_utils.py", line 165, in eager_compute
    driver.run(time_step, policy_state)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\drivers\dynamic_episode_driver.py", line 215, in run
    maximum_iterations=maximum_iterations)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\utils\common.py", line 185, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\drivers\dynamic_episode_driver.py", line 244, in _run
    name='driver_loop'))
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\util\deprecation.py", line 605, in new_func
    return func(*args, **kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2499, in while_loop_v2
    return_same_structure=True)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2735, in while_loop
    loop_vars = body(*loop_vars)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\drivers\dynamic_episode_driver.py", line 134, in loop_body
    action_step = self.policy.action(time_step, policy_state)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\policies\tf_policy.py", line 324, in action
    step = action_fn(time_step=time_step, policy_state=policy_state, seed=seed)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\utils\common.py", line 185, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\policies\tf_policy.py", line 560, in _action
    distribution_step = self._distribution(time_step, policy_state)  # pytype: disable=wrong-arg-types
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\policies\greedy_policy.py", line 81, in _distribution
    time_step, policy_state)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\policies\tf_policy.py", line 403, in distribution
    step = self._distribution(time_step=time_step, policy_state=policy_state)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\agents\ppo\ppo_policy.py", line 255, in _distribution
    time_step, policy_state['actor_network_state'], training=training))
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\agents\ppo\ppo_policy.py", line 231, in _apply_actor_network
    training=training)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\networks\network.py", line 415, in __call__
    outputs, new_state = super(Network, self).__call__(**normalized_kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\networks\actor_distribution_rnn_network.py", line 181, in call
    training=training)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\networks\network.py", line 415, in __call__
    outputs, new_state = super(Network, self).__call__(**normalized_kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\networks\lstm_encoding_network.py", line 254, in call
    **network_kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\keras_layers\dynamic_unroll_layer.py", line 339, in call
    training=training)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\keras_layers\dynamic_unroll_layer.py", line 465, in _dynamic_unroll_multi_step
    maximum_iterations=iterations))
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\util\deprecation.py", line 605, in new_func
    return func(*args, **kwargs)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2499, in while_loop_v2
    return_same_structure=True)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2735, in while_loop
    loop_vars = body(*loop_vars)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2726, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tf_agents\keras_layers\dynamic_unroll_layer.py", line 438, in body
    is_reset = reset_mask_ta.read(time)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 1141, in read
    return self._implementation.read(index, name=name)
  File "C:\Users\kkhanna\.conda\envs\nano_control\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 763, in read
    (index, len(self._tensor_array)))
tensorflow.python.framework.errors_impl.OutOfRangeError: Tried to read from index 1 but array size is: 1
  In call to configurable 'eager_compute' (<function eager_compute at 0x0000021BA4C1DAF8>)
```

However, if the shape set in observation_spec is `[3, 100, 150]` (including the time dimension), the script runs without an error, but the shape of the `random_input` is `[1, 3, 100, 150, 1]` after preprocessing. The call method of LSTMEncodingNetwork then erroneously adds another time dimension, making the shape `[1, 1, 3, 100, 150, 1]`. `batch_squash.flatten` in EncodingNetwork does not handle the actual time dimension, so the Flatten layer actually flattens across the time dimension too. So where the shape after the Flatten layer should have been `[B, 108288]`, the shape is now `[B, 324864]`.
