### ISSUE TITLE
Received a mix of batched and unbatched Tensors, or Tensors are not compatible with Specs.  num_outer_dims: 1

### ISSUE THREAD

**Issue by tinmodeHuang** [tensorflow/agents#596]
I hava the same issue as #266 and #482, my error printed as below:
```bash
tf.Tensor([  1  11 361], shape=(3,), dtype=int32)
TimeStep(step_type=TensorSpec(shape=(), dtype=tf.int32, name='step_type'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)), observation=BoundedTensorSpec(shape=(11, 361), dtype=tf.float32, name='observation', minimum=array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32), maximum=array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)))
Traceback (most recent call last):
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 88, in <module>
    app.run(run_configuration)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/examples/tfa_gnn.py", line 78, in run_configuration
    runner.Train()
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/runners/tfa_runner.py", line 91, in Train
    self.CollectInitialEpisodes()
  File "/home/tinmode/.cache/bazel/_bazel_tinmode/0534ffbce5f0177dc35c2eb30e06c204/execroot/bark_ml/bazel-out/k8-fastbuild/bin/examples/tfa_gnn.runfiles/bark_ml/bark_ml/library_wrappers/lib_tf_agents/runners/tfa_runner.py", line 87, in CollectInitialEpisodes
    self._initial_collection_driver.run()
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 195, in run
    maximum_iterations=maximum_iterations)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/utils/common.py", line 185, in with_check_resource_vars
    return fn(*fn_args, **fn_kwargs)
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/drivers/dynamic_episode_driver.py", line 212, in _run
    self.env.time_step_spec())
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/utils/nest_utils.py", line 717, in get_outer_shape
    nested_tensor, spec, num_outer_dims=num_outer_dims):
  File "/home/tinmode/bark-ml/bark_ml/python_wrapper/venv/lib/python3.7/site-packages/tf_agents/utils/nest_utils.py", line 455, in is_batched_nested_tensors
    tf.nest.pack_sequence_as(specs, spec_shapes)))
ValueError: Received a mix of batched and unbatched Tensors, or Tensors are not compatible with Specs.  num_outer_dims: 1.
Saw tensor_shapes:
   TimeStep(step_type=TensorShape([1]), reward=TensorShape([1]), discount=TensorShape([1]), observation=TensorShape([1, 1, 11, 361]))
And spec_shapes:
   TimeStep(step_type=TensorShape([]), reward=TensorShape([]), discount=TensorShape([]), observation=TensorShape([11, 361]))
```
as you see, the first line shows shape of the observation, the second one shows ```env.time_step_spec()```.
it's my confusion that shape of the observation in ```Saw tensor_shapes``` have extra dimension ```1```against the observation of shape (1, 11, 361).
if only I explained myself!
thanks for your tips in advance

**Comment by ebrevdo** [comment]
It looks like yoour `tensor_shapes` have either a `batch_size=1` or `num_steps=1` for all items except `observation`, which has `[batch_size, num_steps] = [1, 1]` in there.  I think.  Or your env is returning data shaped `[1, 11, 361]` instead of `[11, 361]` as you requested.  If it did the right thing, the final `observation` tensor would be shaped `[1, 11, 361]` and that would be compatible with the rest of the data.
