### ISSUE TITLE
Errors with numpy 1.24.0

### ISSUE THREAD

**Issue by sebastianknopf** [tensorflow/agents#807]
I tried to use tf-agents, the latest version. However, if I run a simple class which only extends PyEnvironment but nothing else, I receive an with a message like 

**module 'numpy' does not contain attribute named 'bool'. Did you mean 'bool_'**

There are several similar issues with numpy, sometimes re-installing numpy helps. In my case it didn't, I tried the common workflow of uninstalling _setuptools_ and _numpy_.

I'm using:

- Python 3.10 (Python 3.11 doesn't work also...)
- Numpy 1.24.0

Is there anything I've left?

**Comment by zsdadisscy** [comment]
I had the same problem I tried lowering the numpy version and it didn't help

**Comment by coreyleveen** [comment]
@sebastianknopf Would you mind sharing your code?

**Comment by sebastianknopf** [comment]
Sadly I can't share any code. I needed to switch to a manual implementation.

Maybe @zsdadisscy can share some code, since facing the same issue?

**Comment by sgboakes** [comment]
Having a similar issue with error **AttributeError: module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?** when importing tf_agents.types. In release 0.15.0, in tf-agents.typing.types.py, line 81 has np.bool. This is not there in the master branch of tf-agents, so I suppose we'll need to wait until this gets pushed to pypi.

**Comment by tfboyd** [comment]
nightly should be working.  numpy 0.24. removed np.bool. Long story and it doesn't matter.  We were preparing for this; but the holiday's slowed us down.  I hope to have an RC and maybe a full release done today.  05-JAN.

**Comment by tfboyd** [comment]
I will ping this thread will progress.

**Comment by tfboyd** [comment]
**Update**: I have not done a root cause but here is the situation and there is nothing I can do until Tensorflow is updated to support Numpy 1.24.0. Keep in mind Numpy 1.24.0 was released at the end of December 2022. 

The tl;dr; is you need to install numpy 1.23.5: `pip install numpy==1.23.5`

Using numpy 1.24.0 causes an error as illustrated by running `python3 -m tf_agents.agents.ppo.ppo_utils_test` but I don't see that error with numpy 1.23.5 keeping everything else exactly the same. 

The error is:
```
======================================================================
ERROR: test_get_distribution_params_WithLegacyDistributionNetwork (__main__.PPOUtilsTest)
PPOUtilsTest.test_get_distribution_params_WithLegacyDistributionNetwork
test_get_distribution_params_WithLegacyDistributionNetwork(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/absl/testing/parameterized.py", line 320, in bound_param_test
    return test_method(self, *testcase_params)
  File "/workspace/tf_agents/agents/ppo/ppo_utils_test.py", line 108, in test_get_distribution_params
    self.assertAllEqual([[[2]], [[2], [2]]],
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/test_util.py", line 1532, in decorated
    return f(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/test_util.py", line 3208, in assertAllEqual
    a = self._GetNdArray(a)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/test_util.py", line 2949, in _GetNdArray
    return np.array(a)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

I did a test with tf-agents-nightly (which then also uses tf-nightly, dm-reverb-nightly, and tfp-nightly). The test worked with numpy 1.23.5 but again failed with numpy 1.24.0 and tf-nightly (tensorflow) throws a warning during the install of numpy 1.24.0 that tensorflow current supports `numpy<1.24,>=1.20`

All of that said, tf-agents has been updated in tf-agents **nightly** to support numpy 0.24.0 by no longer using `np.bool`.

**Comment by sgboakes** [comment]
Thanks for the update!

**Comment by sebastianknopf** [comment]
Thank you too for the update!

**Comment by tfboyd** [comment]
Python 3.11 is now supported in tf-nightly.  Tensorflow 2.12 branch was cut so the next stable will have 3.11.  Numpy is still a mess and I don't think TF has moved to 1.24 yet so there must be some struggles. I keep checking as it is annoying.
