### ISSUE TITLE
AttributeError: module 'tensorflow.python.util.nest' has no attribute 'flatten_with_tuple_paths'

### ISSUE THREAD

**Issue by qhuang-pnl** [tensorflow/agents#89]
AttributeError: module 'tensorflow.python.util.nest' has no attribute 'flatten_with_tuple_paths'

**Comment by oars** [comment]
Do you have a trace of where you are hitting this?

**Comment by qhuang-pnl** [comment]
I have updated Tensorflow to the latest 1.13.1 stable release version. Then run  'python train_eval_gym.py'. Below are the msgs (the error shows up in the end): 

C:\Miniconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "train_eval_gym.py", line 40, in <module>
    from tf_agents.agents.dqn import dqn_agent
  File "C:\Users\myname\AppData\Roaming\Python\Python36\site-packages\tf_agents\agents\__init__.py", line 17, in <module>
    from tf_agents.agents.ddpg.ddpg_agent import DdpgAgent
  File "C:\Users\myname\AppData\Roaming\Python\Python36\site-packages\tf_agents\agents\ddpg\ddpg_agent.py", line 30, in <module>
    from tf_agents.agents import tf_agent
  File "C:\Users\myname\AppData\Roaming\Python\Python36\site-packages\tf_agents\agents\tf_agent.py", line 26, in <module>
    from tf_agents.trajectories import trajectory
  File "C:\Users\myname\AppData\Roaming\Python\Python36\site-packages\tf_agents\trajectories\trajectory.py", line 29, in <module>
    from tf_agents.utils import nest_utils
  File "C:\Users\myname\AppData\Roaming\Python\Python36\site-packages\tf_agents\utils\nest_utils.py", line 28, in <module>
    flatten_with_tuple_paths = nest.flatten_with_tuple_paths
AttributeError: module 'tensorflow.python.util.nest' has no attribute 'flatten_with_tuple_paths'

**Comment by oars** [comment]
You'll need to use `tf-nightly`. Feel free to re-open if you hit this issue on nightly.
