### ISSUE TITLE
Module not found error when working through 1_dqn_tutorial.ipynb

### ISSUE THREAD

**Issue by ace510** [tensorflow/agents#932]
Current Behavior:
when running through the dqn tutorial I get this message
ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'

expected behavior: code in tutorial completes successfully

Error Log:

`Traceback (most recent call last):
  File "/home/ianclark/Github/tf_agent/main.py", line 18, in <module>
    from tf_agents.agents.dqn import dqn_agent
  File "/home/ianclark/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tf_agents/agents/__init__.py", line 17, in <module>
    from tf_agents.agents import tf_agent
  File "/home/ianclark/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tf_agents/agents/tf_agent.py", line 27, in <module>
    from tf_agents.trajectories import time_step as ts
  File "/home/ianclark/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tf_agents/trajectories/__init__.py", line 20, in <module>
    from tf_agents.trajectories import trajectory
  File "/home/ianclark/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tf_agents/trajectories/trajectory.py", line 30, in <module>
    from tf_agents.utils import composite
  File "/home/ianclark/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tf_agents/utils/__init__.py", line 23, in <module>
    from tf_agents.utils import numpy_storage
  File "/home/ianclark/.pyenv/versions/3.12.4/lib/python3.12/site-packages/tf_agents/utils/numpy_storage.py", line 28, in <module>
    from tensorflow.python.training.tracking import base  # TF internal
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'`

**Comment by drakon** [comment]
I'm not 100% sure, but I think I got this error as well and I think it's because of the python 3.12 version, which is I think not yet supported (only 3.8 - 3.11).

**Comment by ace510** [comment]
that got me one step further! thank you @drakon
